[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tsn-adapters"
version = "0.1.0"
description = "A collection of prefect tasks and examples ingesting data into TSN"
readme = "README.md"
dependencies = [
    "prefect-client",
    "truflation-data@git+https://github.com/truflation/truflation.git@deploy-production-20241008",
    "tsn_sdk_py@git+https://github.com/truflation/tsn-sdk-py.git@e168b53e4c9e53e198b439208c9b5103fe551c5f",
    "PyGithub",
]

[tool.setuptools]
packages = {find = {where = ["src"]}}
